# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: zuhairalzikri
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
